//
// Copyright Coinbase, Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

package common

import (
	"git.sonr.io/pkg/crypto/core/curves"
)

// Challenge generated by fiat-shamir heuristic
type Challenge = curves.Scalar
